config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


get "/jquery-1" => "pages#jquery_1"
get "/jquery-2" => "pages#jquery_2"
get "/jquery-3" => "pages#jquery_3"
get "/jquery-4" => "pages#jquery_4"
get "/jquery-5" => "pages#jquery_5"

root "posts#index"

   resources :posts do
     member do
       post "like" => "posts#like"
       post "unlike" => "posts#unlike"
       post "toggle_flag" => "posts#toggle_flag"
     end
   end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
has_many :posts
end

app/models/like.rb
class Like < ApplicationRecord
   belongs_to :user
   belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :content
  belongs_to :user

  has_many :likes, :dependent => :destroy
  has_many :liked_users, :through => :likes, :source => :user

  def find_like(user)
   self.likes.where( :user_id => user.id ).first
  end

  belongs_to :category, :optional => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts

      def display_name
        # # 取 email 的前半來顯示，如果你也可以另開一個字段是 nickname 讓用戶可以自己編輯顯示名稱
        self.email.split("@").first
      end

  has_many :likes, :dependent => :destroy
  has_many :liked_posts, :through => :likes, :source => :post

  def is_admin?
    role == "admin"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

 before_action :authenticate_user!, :only => [:create, :destroy]

  def index
    @posts = Post.order("id DESC").limit(20)

    if params[:max_id]
      @posts = @posts.where( "id < ?", params[:max_id])
    end

    respond_to do |format|
      format.html #客戶要求HTML 則回傳 index
      format.js   #客戶端要求 JavaScript 回傳 index.js.erb
    end
  end


  def create
    @post = Post.new(post_params)
    @post.user = current_user
    @post.save

  end

def update
   sleep(1)
  @post = Post.find(params[:id])
  @post.update!( post_params )
  render :json => { :id => @post.id, :message => "ok"}
end

  def destroy
    @post = current_user.posts.find(params[:id]) # 只能刪除自己的貼文
    @post.destroy

      render :json => { :id => @post.id }
  end

  def like
     @post = Post.find(params[:id])
     unless @post.find_like(current_user)  # 如果已經按讚過了，就略過不再新增
       Like.create( :user => current_user, :post => @post)
     end

   end

   def unlike
     @post = Post.find(params[:id])
     like = @post.find_like(current_user)
     like.destroy

     render "like"
   end

   def toggle_flag
     @post = Post.find(params[:id])

     if @post.flag_at
       @post.flag_at = nil
     else
       @post.flag_at = Time.now
     end

     @post.save!

     render :json => { :message => "ok", :flag_at => @post.flag_at, :id => @post.id }
   end

  protected

  def post_params
    params.require(:post).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>AjasExercise</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= javascript_include_tag 'application' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% if flash[:notice] %>
           <%= flash[:notice] %>
         <% end %>

         <% if flash[:alert] %>
           <%= flash[:alert] %>
         <% end %>

        <% if current_user %>
           <%= link_to('登出', destroy_user_session_path, :method => :delete) %>
          <%= link_to('修改密碼', edit_registration_path(:user)) %>
        <% else %>
          <%= link_to('註冊', new_registration_path(:user)) %> |
          <%= link_to('登入', new_session_path(:user)) %>
         <% end %>


    <%= link_to "JQuery Paratices 1", jquery_1_path %>  |
    <%= link_to "JQuery Paratices 2", jquery_2_path %>  |
    <%= link_to "JQuery Paratices 3", jquery_3_path %>  |
    <%= link_to "JQuery Paratices 4", jquery_4_path %>  |
    <%= link_to "JQuery Paratices 5", jquery_5_path %>
        <%= yield %>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg OMhuP IlRH9sENBO0LRn5q 8nbTov4 1p" crossorigin="anonymous"></script>

    </div>
  </body>
</html>

app/views/pages/jquery_1.html.erb
<script>
// 這是javascript 註解
// 也可以寫成 $(function() {}
$(document).ready(function(){
  $("#my-click").click(function(){
    $("#foo").after('<h1>Z00</z1>')
  })
})
</script>


  <p>
    <a id="my-click">Click me</a>
  </p>



  <div id="foo" stytle="border: 1px solid red;">
    <p>bar</p>
  </div>

app/views/pages/jquery_2.html.erb
<p>
  <a id="my-open-click">Open</a>
</p>

<div id="foo" style="border: 1px solid red;">
  <a id="my-hide-click">Hide</a>
  <p>bar</p>
</div>


<script>
  $("#foo").slideUp();

  $("#my-open-click").click(function(){
    $("#foo").slideDown();
  })

  $("#my-hide-click").click(function(){
    $("#foo").slideDown();
  })

</script>

app/views/pages/jquery_3.html.erb
<p>
    <a id="my-toggle-click">Toggle</a>
</p>

<div id="foo" style="border: 1px solid red;">
  <p>bar</p>
</div>

<script>
  $("#foo").hide(); //馬上藏起來

  $("#my-toggle-click").hover(function(){
    $("#foo").fadeToggle(); //移過去會有開關消過
  })

</script>

app/views/pages/jquery_4.html.erb
<p>
  <a id="my-replace-click">Replace</a>
  <a id="my-remove-click">Remove</a>
  <a id="my-remove-all-click">Remove All</a>
</p>

<div id="foo" style="border": 1px solid red;>
  <p>bar</p>
</div>

<div class="zoo"><p>a</p></div>
<div class="zoo"><p>b</p></div>
<div class="zoo"><p>c</p></div>

<script>
  $("#my-replace-click").click(function(){
   $("#foo").replaceWith('<div id="foo" style="border:1px solid green"><p>foo</p></div>');
  })

  $("#my-remove-click").click(function(){
      $("#foo").remove();
    })

  $("#my-remove-all-click").click(function(){
    $(".zoo").remove();
  })
</script>

app/views/pages/jquery_5.html.erb
<style>
  .error {
    color: red;
  }
  .success {
    color: green;
  }
</style>

<p>
  <a id="my-add-class-click">Add Class</a>

  <a id="my-remove-class-click">Remove Class</a>
</p>

<div id="foo">
  <h1>bar</h1>
</div>

<script>
  $("#my-add-class-click").click(function(){
    $("#foo").removeClass('error');
    $("#foo").addClass('success');
  })

  $("#my-remove-class-click").click(function(){
    $("#foo").removeClass('success');
    $("#foo").addClass('error');
  })
</script>

app/views/posts/_like.html.erb
<% if post.liked_users.any? %>
  <%= post.liked_users.map{ |u| u.display_name }.join(",") %> 點了讚
<% end %>

<% if current_user # 有登入才能按讚 %>
  <% if post.find_like(current_user) %>
    <%= link_to "取消讚", unlike_post_path(post), :method => :post, :remote => true, :class => "btn btn-primary" %>
  <% else %>
     <%= link_to "讚", like_post_path(post), :method => :post, :remote => true, :class => "btn btn-primary" %>
  <% end %>
 <% end %>

app/views/posts/_post.html.erb
<div id="post-<%= post.id %>" class= "panel panel-default">
  <div class="panel-heading"><%= post.user.display_name %></div>
  <div class="panel-body">
    <%= post.content %>
    <span id="post-thumbsup-<%= post.id %>" class="label label-success"><%= post.likes.count %> 👍</span>

    <div class="raty"></div>
    
    <div class="text-right">

  <span id="post-like-<%= post.id %>">
    <%= render :partial => "like", :locals => { :post => post } %>
  </span>

    <% if current_user && post.user == current_user %>
      <p class="text-right">
        <%= link_to "Delete", post_path(post), :class => "delete-post btn btn-danger" %>
      </p>
    <% end %>
    </div>
  </div>
</div>


<div class="panel-footer">
  <% if current_user && current_user.is_admin? %>
    <%= select_tag "category_id[#{post.id}]", options_for_select(Category.all.map{ |x| [x.name, x.id]}, post.category_id),
        :data => { :url => post_path(post) }, :prompt => "Please Choose category", :class => "select_category" %>

  <label>
    <%= check_box_tag "mark_flag[#{post.id}]", 1, post.flag_at.present?,
            :data => { :url => toggle_flag_post_path(post) }, :class => "toggle-flag" %> 標記為垃圾
        <span id="post-flag-<%= post.id %>"><%= post.flag_at %></span>
      </label>
    <% end %>
  </div>

app/views/posts/create.js.erb
 <% if @post.valid? %>
$("#post-list").prepend("<%=j render :partial => "post", :locals => { :post => @post } %>");
$("#post_content").val("");
<% else %>
  alert("貼文失敗");
<% end %>

app/views/posts/index.html.erb
<%= form_for Post.new, :remote => true do|f| %>
  <div clas="form-group">
    <%= f.text_area :content, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>
<div id="post-list">
<% @posts.each do |post| %>


   <%= render :partial => "post", :locals => { :post => post } %>
<% end %>

</div>

<script>
   // 這會綁 click 事件到所有有 `.delete-post` class 的元素上，也就是所有的刪除按鈕
   $("#post-list").on('click', ".delete-post", function(evt){

     // `evt` 是瀏覽器的事件物件，evt.preventDefault(); 會終止這個元素的預設行為：
     // 超連結 a 的預設行為是跳到下一頁，如果沒有這行的話，送出 ajax 後會跳去 show page
     evt.preventDefault();
      // this 是個特別的變數，代表觸發事件的元素。使用 attr 可以讀取元素的屬性，這裡要拿到超連結的網址
      var url = $(this).attr("href");
      var that = this;

      // 送出 Ajax
      $.ajax({
        url: url,
        method: 'DELETE',
        dataType: 'json', // 要求伺服器回傳 json
        success: function(data){   // data 就是伺服器回傳的 JSON 資料
          $(that).closest(".panel").remove();
        }
      })
   })

</script>


<script>
  //紀錄畫面最小的貼文id
  $(window).scroll(function(){
    //當捲到最下面時
    if ((window.innerHeight + window.scrollY) >= document.body.offsetHeight) {
      var url = "/posts?max_id=" + current_post_id;
      if (url) {
        $.ajax({
          method: "GET",
          url: url,
          dataType: "script"
        })
      } else {
        console.log("data ended")
      }
    }
  })


</script>


<script>
  $(".toggle-flag").on('change', function(){
    var url = $(this).data("url");

    $.ajax({
      url: url,
      method: "POST",
      dataType: "json",
      success: function(data){
        if ( data["flag_at"] ) {
         $("#post-flag-" + data["id"]).html(data["flag_at"]);
        } else {
          $("#post-flag-" + data["id"]).html("");
        }
      }
    });
  });
 </script>


 <script>
   $("#post-list").on('change', ".select_category", function(){
     var url = $(this).data("url");
     var that = this;

    $.ajax({
       url: url,
       method: "PATCH",
       dataType: "json",
       data: {
         post: {
           category_id: $(this).val()
         }
       },
        beforeSend: function(){
          $(that).after( $(' <img src="/images/ajax-loader.gif" id="ajax-loading"> ') );
        },
        complete: function(){
          $("#ajax-loading").remove();
        }
     });
   });
  </script>


  <script>
    $(".raty").raty( { path: '/images/' } );
 </script>

app/views/posts/index.js.erb
<% @posts.each do |post| %>
  $("#post-list").append("<hr>")
  $("#post-list").append("<%=j render :partial => "post", :locals => { :post => post } %>");
<% end %>

<% if @posts.any? %>
var current_post_id = <% @posts.last.id %>;
<% end %>

app/views/posts/like.js.erb
str = "<%=j render :partial => "like", :locals => { :post => @post } %>";
$("#post-like-<%= @post.id %>").html(str);


$("#post-thumbsup-<%= @post.id %>").html("<%= @post.likes.count %>" + " 👍")